# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('cons_id', models.IntegerField(db_column='Cons_id')),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
