# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('cons_id', models.AutoField(db_column='Cons_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=25)),
                ('address', models.CharField(db_column='Address', max_length=25)),
                ('contact_no', models.CharField(db_column='Contact_no', max_length=25)),
                ('email_id', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'consumer',
                'managed': False,
            },
        ),
    ]
