# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(db_column='E_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=25)),
                ('age', models.IntegerField(db_column='Age')),
                ('address', models.CharField(db_column='Address', max_length=25)),
                ('department', models.CharField(db_column='Department', max_length=25)),
                ('salary', models.IntegerField(db_column='Salary')),
                ('contact_no', models.CharField(db_column='Contact_no', max_length=10)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
