# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_id', models.IntegerField()),
                ('cons_id', models.IntegerField(db_column='Cons_id')),
                ('bill_amount', models.CharField(max_length=11)),
                ('payment_method', models.CharField(db_column='payment method', max_length=25)),
                ('payment_status', models.CharField(db_column='payment status', max_length=25)),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
