# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('conn_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_id', models.IntegerField()),
                ('cons_id', models.IntegerField(db_column='Cons_id')),
                ('request', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'connection',
                'managed': False,
            },
        ),
    ]
