# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReading',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_id', models.IntegerField(db_column='Cons_id')),
                ('o_id', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'image_reading',
                'managed': False,
            },
        ),
    ]
