# Generated by Django 3.2.15 on 2022-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_id', models.IntegerField(db_column='E_id')),
                ('o_id', models.IntegerField()),
                ('work', models.CharField(max_length=25)),
                ('work_status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'work',
                'managed': False,
            },
        ),
    ]
